[package]
name = "fastrank"
version = "0.1.0"
authors = ["John Foley <jjfoley@smith.edu>"]
edition = "2018"

[dependencies]
ordered-float = "1.0"
rand = "0.7"
bzip2 = "0.3"
flate2 = "1.0"
zstd = "0.4"
clap = "1.0"